# docker-compose.yml

version: '3.8' # Specify the Docker Compose file format version

services:
  qdrant:
    image: qdrant/qdrant:latest # Use the latest official Qdrant Docker image
    container_name: qdrant_db   # Assign a recognizable name to the container
    restart: unless-stopped     # Ensure the container restarts automatically unless explicitly stopped

    ports:
      - "6333:6333" # Map host port 6333 to container port 6333 (HTTP API)
      - "6334:6334" # Map host port 6334 to container port 6334 (gRPC API)
      # You can also map the UI port if you want to use the Qdrant UI:
      - "8080:8080" # Map host port 8080 to container port 8080 (Web UI)

    volumes:
      # Mount a named volume to persist Qdrant data.
      # 'qdrant_data' is the name of the Docker volume defined below.
      # '/qdrant/storage' is the default directory where Qdrant stores its data inside the container.
      - qdrant_data:/qdrant/storage

    # Environment variables for Qdrant (optional, but good for configuration)
    environment:
      # Set Qdrant's log level (e.g., INFO, DEBUG, WARN, ERROR)
      - QDRANT__LOG_LEVEL=INFO
      # You can add more Qdrant specific environment variables here if needed
      # Refer to Qdrant documentation for available options.

volumes:
  # Define the named volume. Docker manages this volume,
  # and its data will persist even if the 'qdrant' container is removed.
  qdrant_data:
    driver: local # Use the local driver for volume storage (default)
